apiVersion: v1
kind: Pod
metadata:
  name: leases
spec:
  containers:
    - name: leases
      image: ko://github.com/skonto/test-k8s/cmd/leases
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 400m
          memory: 500Mi
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name